import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import fetcher from '../utils/fetcher'
import { useRandomImage } from '../hooks/useRandomImage'
import ImagePlaceholder from '../utils/ImagePlaceholder'

const inter = Inter({ subsets: ['latin'] })

export default function Home({
  roversMetadata
}) {


  const { roversNames, currentPhotos, currentRover } = useRandomImage(roversMetadata)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {currentRover &&
          <div style={{ display: 'flex',flexDirection:'column' }}>
            <h3>Rover: {currentRover.name}</h3>
            <h3>Launch date: {currentRover.launch_date}</h3>
            <h3>Landing date: {currentRover.landing_date}</h3>
            <h3>Mission status: {currentRover.status}</h3>
          </div>
        }
        <div className={styles.container}>
          {currentPhotos && <Features features={currentPhotos} />}
        </div>
      </main>
    </>
  )
}

const Features = ({ features }) =>
  <div className={styles.gallery}>
    {features.map((feature, i) =>
      <ImagePlaceholder  {...feature} key={i} />
    )}
  </div>

export async function getStaticProps() {
  const isDevMode = process.env.NODE_ENV !== 'production'
  // TODO add production URL
  // Checking if the app is in development mode.
  // The base URL must be included when calling another API from here.
  const baseURL = isDevMode ? 'http://localhost:3000' : ''
  const { roversMetadata } = await fetcher(`${baseURL}/api/roversMetadata`)
  return { props: { roversMetadata } }
}